"""initial

Revision ID: 644ccf36e0f4
Revises: 
Create Date: 2026-05-13 11:06:39.113901

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '644ccf36e0f4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('videos_used_this_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('briefs',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('template_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('key_claims', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('target_platform', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('custom_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_user_id'), 'briefs', ['user_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('identity_verifications',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('persona_id', sa.TEXT(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_inquiry_id', sa.String(length=255), nullable=True),
    sa.Column('provider_session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_verifications_persona_id'), 'identity_verifications', ['persona_id'], unique=False)
    op.create_table('source_clips',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('persona_id', sa.TEXT(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('framing_score', sa.Float(), nullable=True),
    sa.Column('audio_score', sa.Float(), nullable=True),
    sa.Column('lighting_score', sa.Float(), nullable=True),
    sa.Column('face_visibility_score', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_clips_persona_id'), 'source_clips', ['persona_id'], unique=False)
    op.create_table('voice_profiles',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('persona_id', sa.TEXT(), nullable=False),
    sa.Column('prompt_audio_path', sa.String(length=500), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('sample_duration', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_persona_id'), 'voice_profiles', ['persona_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('persona_id', sa.TEXT(), nullable=False),
    sa.Column('brief_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_clip_id', sa.TEXT(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('script_source', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['source_clip_id'], ['source_clips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_brief_id'), 'projects', ['brief_id'], unique=False)
    op.create_index(op.f('ix_projects_persona_id'), 'projects', ['persona_id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.TEXT(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('source_clip_id', sa.TEXT(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=False),
    sa.Column('start_word_index', sa.Integer(), nullable=False),
    sa.Column('end_word_index', sa.Integer(), nullable=False),
    sa.Column('duration_estimate', sa.Float(), nullable=False),
    sa.Column('tts_status', sa.String(length=50), nullable=True),
    sa.Column('lipsync_status', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_clip_id'], ['source_clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_project_id'), 'segments', ['project_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.TEXT(), nullable=False),
    sa.Column('segment_id', sa.TEXT(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_segment_id'), 'assets', ['segment_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.TEXT(), nullable=False),
    sa.Column('segment_id', sa.TEXT(), nullable=True),
    sa.Column('evaluator_model', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('lip_sync_quality', sa.String(length=50), nullable=True),
    sa.Column('voice_match', sa.String(length=50), nullable=True),
    sa.Column('visual_quality', sa.String(length=50), nullable=True),
    sa.Column('temporal_coherence', sa.String(length=50), nullable=True),
    sa.Column('overall_realism', sa.String(length=50), nullable=True),
    sa.Column('caption_quality', sa.String(length=50), nullable=True),
    sa.Column('cta_present', sa.Boolean(), nullable=True),
    sa.Column('audio_quality', sa.String(length=50), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('critical_issues', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('fix_strategy', sa.String(length=50), nullable=True),
    sa.Column('fix_result', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_project_id'), 'evaluation_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_segment_id'), 'evaluation_results', ['segment_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('project_id', sa.TEXT(), nullable=True),
    sa.Column('segment_id', sa.TEXT(), nullable=True),
    sa.Column('persona_id', sa.TEXT(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.String(length=500), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_persona_id'), 'jobs', ['persona_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_segment_id'), 'jobs', ['segment_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_segment_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_persona_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_evaluation_results_segment_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_project_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_assets_segment_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_segments_project_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_persona_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_brief_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_voice_profiles_persona_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_source_clips_persona_id'), table_name='source_clips')
    op.drop_table('source_clips')
    op.drop_index(op.f('ix_identity_verifications_persona_id'), table_name='identity_verifications')
    op.drop_table('identity_verifications')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_briefs_user_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
